// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { normalizePostgresDatabaseUrl } from "./lib/db-connection-string";

/**
 * Returns datasource URL for Prisma CLI with sslmode normalized for `pg` (no deprecation warnings).
 */
function getDatasourceUrl(): string | undefined {
  const raw = process.env["DATABASE_URL"];
  if (!raw) {
    return undefined;
  }
  return normalizePostgresDatabaseUrl(raw);
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    /** Matches `package.json` `prisma.seed` so `npx prisma db seed` runs the same script as `npm run seed`. */
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: getDatasourceUrl(),
  },
});
